### PR TITLE
Don't suggest make -jN, and invoke heimdall with sudo

### PR DESCRIPTION
**Pull request by jlebar**

### CODE REVIEW

**Comment by jlebar** [comment]
mwu says sudo heimdall is not necessary on mac.  It is on my machine, though.  Maybe there's some configuration I can frob.

**Comment by andreasgal** [comment]
Feel free to merge trivial stuff on your own. And thanks for the patch!

**Comment by joneschrisg** [comment]
I would be very very nervous running heimdall with su privs.  You just need to set up udev rules for your devices:

http://developer.android.com/guide/developing/device.html#setting-up

**Comment by jlebar** [comment]
Ah, I didn't realize that I needed to set up a separate rule for my Nexus S and my Galaxy S II.

**Comment by jlebar** [comment]
I set up a separate rule, and heimdall still doesn't work.

Is your heimdall setuid'ed?

$ make flash
[snip]
Detecting device...
libusb couldn't open USB device /dev/bus/usb/002/058: Permission denied.
libusb requires write access to USB device nodes.
ERROR: Failed to access device. libusb error: -3

$ cat /etc/udev/rules.d/51-android.rules 
SUBSYSTEM=="usb", ATTR{idVendor}=="18D1", MODE="0666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTR{idVendor}=="04E8", MODE="0666", GROUP="plugdev"

**Comment by joneschrisg** [comment]
$ cat /etc/udev/rules.d/51-android.rules 
SUBSYSTEM=="usb", SYSFS{idVendor}=="04e8", MODE="0666"
SUBSYSTEM=="usb", SYSFS{idVendor}=="22b8", MODE="0666"
SUBSYSTEM=="usb", SYSFS{idVendor}=="18d1", MODE="0666"

So hm, not sure what's up.  I don't think the GROUP setting should make a difference, but maybe try dropping that and see if heimdall works?

**Comment by jlebar** [comment]
Just tried that; doesn't work.

Any other ideas?

On Wed, Oct 19, 2011 at 2:42 AM, Chris Jones
reply@reply.github.com
wrote:

**Comment by joneschrisg** [comment]
Just to be sure, are you |service udev restart| after adding the rules?  There are some places on the internet that claim you might need to log out and log back in but I don't believe them.  Might also be worth a shot.

**Comment by shianyow** [comment]
The ATTR{idVendor} seems case sensitive.
Try change vendor ID to lower case(04E8 -> 04e8), unplug/plug usb cables, then see if it works.

sywu@sywu-desktop:~$ cat /etc/udev/rules.d/51-android.rules
SUBSYSTEM=="usb", ATTR{idVendor}=="04e8", MODE="666", GROUP="plugdev"
sywu@sywu-desktop:~$ ls -l /dev/bus/usb/001
total 0
crw-rw-r-- 1 root root    189,  0 2011-10-20 00:49 001
crw-rw-r-- 1 root root    189,  1 2011-10-20 00:49 002
crw-rw-rw- 1 root plugdev 189, 23 2011-10-20 22:10 024
sywu@sywu-desktop:~$

**Comment by jlebar** [comment]
Hooray, that worked!  Thanks.

**Pull request closed without merging**
