### PR TITLE
Fix makefile

### PR DESCRIPTION
**Pull request by mikeaich**
The install-valgrind target has a bug in the symlink command; this change fixes it.

### CODE REVIEW

**Comment by michaelwu** [comment]
Can you make a pull request with just that change?

**Comment by mikeaich** [comment]
That pull request should just be that one change.  The other changes are from me rolling back to an earlier rev of the file so that you wouldn't pick up everything I had tweaked.

----- Original Message -----

**Comment by michaelwu** [comment]
I mean just one commit. Squash the commits together with interactive rebase and submit another pull request.

**Comment by mikeaich** [comment]
How do I do that?

----- Original Message -----

**Comment by michaelwu** [comment]
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by mikeaich** [comment]
I did the interactive rebase, squashing my changes together, and the result is a Makefile that has a bunch of extra stuff in it that isn't ready yet and doesn't work, in addition to the bug fix I wanted to push upstream.

----- Original Message -----

**Pull request closed without merging**
