### PR TITLE
Make gecko depends on gonk.

### PR DESCRIPTION
**Pull request by ThinkerYzu**
- Gecko should be built after building gonk.
- Rebuild system.img at gecko-*-hack.

### CODE REVIEW

**Comment by jlebar** [comment]
This is going to make gecko development within B2G even more annoying than it already is, because now every time I want to build gecko, I'll have to wait for a nop gonk build to go through.  :(

**Comment by michaelwu** [comment]
Very nice.

To address jlebar's concern, we can probably check to see if we have one of those crt\* files and add a rule which depends on/makes gonk.

**Comment by ThinkerYzu** [comment]
How about to introduce a gecko-only?

**Comment by jlebar** [comment]
I'd be satisfied with gecko-only, but I'd prefer mwu's idea, if that's practical.  Otherwise, I have to make gecko-only, then, once that compiles, make flash, which will now go through a nop gecko build.

I wish build wasn't so crummy...

**Comment by ThinkerYzu** [comment]
Currently, |flash| depends on |build| target.  It always go through nop targets, even check crt\* files for gecko.  One way to avoid it is to touch a timestamp file for every target.  However, you must remove timestampe files or run |clean-*| targets to force targets to be rebuilt.  Is it what you want?

There is a |flash-only| target, now.  It may save your time.  But, you should run gecko-android-hack or gecko-gonk-hack to create system image before flashing.

**Comment by jlebar** [comment]
> There is a |flash-only| target, now. It may save your time. But, you should run gecko-android-hack or gecko-gonk-hack 
> to create system image before flashing.

I guess I could run |make gecko-only && make gecko-gonk-hack && make flash-only|.  It would be nice if we didn't have to do this, though.

> However, you must remove timestamp files or run |clean-*| targets to force targets to be rebuilt. Is it what you want?

No.  That would be too much trouble, I think, and it breaks the "just build it" concept of make.

But maybe we can do this automatically.  When you finish a build, increase the timestamps of all the non-source files (the products of the build) so that the relative ordering of the times is preserved, but they're all stamped newer than the newest source file.  When you start a build, check if all the source files are older than the oldest non-source file.  If so, skip the nop build.

git ls-files lists the source files.  We'd have to do some work to make it recursive into the sub-repositories, but that shouldn't be to hard.

Could that work?

**Comment by ThinkerYzu** [comment]
The idea of timestamps for generated files are almost doing dependency checking, doing by make originally, by our-self.  How much can we gain from it?  I am not sure.

It is more easy to touch a timestamps for each submodule of gecko, kernel, and gonk, and check modified time of timestamp files against source files to decide whether build them.  I can try it with a little work, and see what can we gain from it.

**Comment by ThinkerYzu** [comment]
This patch check dependency by checking hash of last modification time and file names.  kernel, gonk, and gecko are built only for changes of hash value.

**Comment by jlebar** [comment]
Hey, this is cool!  How long does it take to run this check?

One problem I realized with this approach is that if you create a new source file but don't |git add| it, we won't notice changes to the file and therefore won't always rebuild when we should.  This seems like a pretty important problem to solve.

If we ensured that .gitignore files always ignored all object files, then we could do |git ls-files --others|.  I know we'd have to fix at least gecko's .gitignore.

Also, do we know that the order of files returned by git ls-files is stable?  Maybe we should sort first?

**Comment by ThinkerYzu** [comment]
For |build| target, it is about 31s with my box.  But, it is longer (2m23s) for a just cold booted box.
|git submodule| spends a lot of time.  It is about 12s to run |make| if cache result of |git submodule| in a file or use content of .gitsubmodules.

For new source files, you can |git add| temporary, and drop them later if you don't need them anymore.  |git ls-files --others| sounds good, but, as you said, .gitignore must be set carefully.  We have a lot of submodule, we should set .gitignore for every one carefully.

In my tests, |git ls-files| seems stable, but your concern is reasonable.  I will change it to do sorting before hashing.

**Comment by jlebar** [comment]
I just checked, and on my machine, with a full gonk (but not Android) build, git status reports untracked content only in gecko (due to the objdir not being in gitignore).  So maybe we can rely on git ls-files --others, if we just check an Android build.  I'd rather do that than try to make everyone aware of the fact that they need to git add their files before building.

12 seconds of overhead seems acceptable to me.  I'd be in favor of taking out |sort| if that would make it faster, though.  :)

**Comment by ThinkerYzu** [comment]
Last change need to add objdir-prof-android/\* into .gitignore of gecko.

**Comment by ThinkerYzu** [comment]
|sort| spends ignorable time.  So, I keep it to make sure not effected by changes of git implementation.

**Comment by jlebar** [comment]
We could make the |gecko| target depend on gonk and the |install-gecko| target not depend on gonk.  Then we wouldn't really need this hackery.

**Comment by jlebar** [comment]
See issue #97 -- Apparently we have to make gonk both before and after we make gecko?  That's unfortunate.

Once we fix issue #82 and make install-gecko works with gonk builds, then we can make the default |make| run as slowly as we want, and we don't need any of the hacks we've discussed here, I think.

**Comment by joneschrisg** [comment]
We have to make gonk the first time to build the libs gecko depends on.  The second time is to make the system image.  E could do those with more fine grained commands if there's a benefit.

**Comment by jlebar** [comment]
> We have to make gonk the first time to build the libs gecko depends on.

Understood.  But do we always have to make gonk _after_ gecko is rebuilt?

**Comment by joneschrisg** [comment]
For the default make target, yes, as I said above, to rebuild the system image.

For make gecko, no.

**Comment by joneschrisg** [comment]
Note that we have a |make install-gecko| target now that rebuilds gecko and copies it to device.

**Comment by joneschrisg** [comment]
@ThinkerYzu this is seriously cool, I don't know how we lost track of it :(.

It's been bitrotted, but I would love to merge this in.  Can you please rebase on tip?

**Comment by joneschrisg** [comment]
Also, the linux kernel's and android's build system are much much better than gecko's build system (frankly, gecko's build system sucks).  My depend builds with linux and android have been quite fast.  Did you measure if using this hash check wins much for linux and android?  If there's not much improvement, I'd prefer to keep those steps simple.

(This will definitely make gecko builds faster.)

**Comment by ThinkerYzu** [comment]
|make kernel| is 11s VS 0.1s, |make gonk| is 11s VS 0.1s, and |make gecko| is 1m VS 0.54s.  You can disable it by setting STOP_DEPENDENCY_CHECK to any value other than false.  For example, |make STOP_DEPENDENCY_CHECK=true|.

**Comment by joneschrisg** [comment]
Awesome!

**Pull request merged**
